### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by nicholasadr** [roboticsleeds/ur5controller#11]
Hi, I am trying to follow the instructions that you provide, but unfortunately the link on configuring or_urdf is broken: http://computingstories.com/robotics%20stories/installing-or_urdf-openrave-plugin.html. Any chance that you have it somewhere else?

**Comment by rpapallas** [comment]
Hi,

Sure, I just uploaded it [here](https://gist.github.com/rpapallas/171cad0e881769647d0851b8780cc545).

Let me know if you have any other problems running ur5controller.
