### ISSUE TITLE
Unique IK solution

### ISSUE THREAD

**Issue by robopassio** [roboticsleeds/ur5controller#12]
For other robots, we can get multiple IK solutions. However, for UR5, I only can get one IK solution for every configuration using:
```
ik_solution = self.robot.manipulator.FindIKSolution(start_transform, IkFilterOptions.CheckEnvCollisions)
```
Is that normal with UR robots?
I have tried to change the flag `CheckEnvCollisions` but nothing change.

**Comment by rpapallas** [comment]
Did you try `FindIKSolutions` (note the s)?
