### ISSUE TITLE
./control_ur5.py has trajectory_object, I am trying to read trajectory inside trajectory_object

### ISSUE THREAD

**Issue by lakshmip001** [roboticsleeds/ur5controller#8]
For the following lines of code:
way_points = trajectory_object.GetWaypoints2D(0, trajectory_object.GetNumWaypoints())
                print "trajectory_object"
                print way_points
                planningutils.RetimeTrajectory (trajectory_object, hastimestamps=True, maxvelmult=0.5, maxaccelmult=0.5)
                new_waypoints = trajectory_object.GetWaypoints2D(0, trajectory_object.GetNumWaypoints())
                print "new_waypoints"
                print new_waypoints

gives following output:
Menu Action: d
ik_solution
[-0.35203007 -2.2471289  -0.82091772 -3.21502544 -0.42179542 -3.14166423]
trajectory_object
[[ -1.05592806e+00  -1.49860460e+00  -1.80591137e+00  -2.97861797e+00
   -1.12569410e+00  -3.14158303e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   1.00000000e+00]
 [ -1.05564221e+00  -1.49890857e+00  -1.80551137e+00  -2.97871397e+00
   -1.12540825e+00  -3.14158306e+00   1.42924371e-01  -1.51985610e-01
    2.00000000e-01  -4.80018264e-02   1.42924512e-01  -1.64882459e-05
    4.00000000e-03   0.00000000e+00]
 [ -3.52315918e-01  -2.24682493e+00  -8.21317722e-01  -3.21492944e+00
   -4.22081271e-01  -3.14166420e+00   1.42924371e-01  -1.51985610e-01
    2.00000000e-01  -4.80018264e-02   1.42924512e-01  -1.64882459e-05
    4.92096822e+00   0.00000000e+00]
 [ -3.52030070e-01  -2.24712890e+00  -8.20917722e-01  -3.21502544e+00
   -4.21795422e-01  -3.14166423e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    4.00000000e-03   1.00000000e+00]]
<configuration dof="14">
new_waypoints
[[ -1.05592806e+00  -1.49860460e+00  -1.80591137e+00  -2.97861797e+00
   -1.12569410e+00  -3.14158303e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   1.00000000e+00]
 [ -1.05564221e+00  -1.49890857e+00  -1.80551137e+00  -2.97871397e+00
   -1.12540825e+00  -3.14158306e+00   1.42924371e-01  -1.51985610e-01
    2.00000000e-01  -4.80018264e-02   1.42924512e-01  -1.64882459e-05
    4.00000000e-03   0.00000000e+00]
 [ -3.52315918e-01  -2.24682493e+00  -8.21317722e-01  -3.21492944e+00
   -4.22081271e-01  -3.14166420e+00   1.42924371e-01  -1.51985610e-01
    2.00000000e-01  -4.80018264e-02   1.42924512e-01  -1.64882459e-05
    4.92096822e+00   0.00000000e+00]
 [ -3.52030070e-01  -2.24712890e+00  -8.20917722e-01  -3.21502544e+00
   -4.21795422e-01  -3.14166423e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    4.00000000e-03   1.00000000e+00]]
Menu Action: exit

I didnt get why I get 14 DOF . Kindly please help me to get trajectory with timestamps , and joint values, joint velocities & joint accelerations

**Comment by rpapallas** [comment]
Please use the OpenRAVE mailing list [here](http://openrave-users-list.185357.n3.nabble.com/) for OpenRAVE-related questions. Questions here are only related to ur5controller issues and bugs.

In short, the waypoints are not only including DOF values but other information about the waypoint as well, so the 14 values you see are not DOF values only.
